### PR TITLE
Remove `TimeLogManager` and make `TimeLogger` singleton

### PR DESCRIPTION
**Pull request by schnellerhase**
Fixes https://github.com/FEniCS/dolfinx/issues/3480

### CODE REVIEW

**Comment by garth-wells** [comment]
What's the advantage of a monostate design over a singleton? Looks to me to all intents and purposes to be the same thing.

**Comment by schnellerhase** [comment]
I think in this case it results in the same. We can decide on the interface we prefer, rather calling some kind of an `instance` function in the singleton approach or the constructor as here with the monostate.

**Comment by schnellerhase** [comment]
Shall we stick to the monostate or return to the singleton approach, just within `TimeLogger` now?

**Comment by jhale** [comment]
After reading the comments I would recommend singleton - as @garth-wells says there is little clear advantage, and singleton is at least well-known (and people understand the issues).

**Pull request merged**
