### PR TITLE
Simplify Docker image hierarchy

### PR DESCRIPTION
**Pull request by jhale**
I propose three concrete images in this new `Dockerfile`: `dolfinx/dev-env`, `dolfinx/dolfinx` and `dolfinx/lab`.

Still TODO:
1. Shell script to switch between dolfinx in real and complex modes.
2. Update CircleCI (and/or GH actions) nightly builds.

### CODE REVIEW

**Comment by garth-wells** [comment]
Do we need `dolfinx/dev-env`? Doesn't look much different to `https://hub.docker.com/r/fenicsproject/test-env`. Also a bit weird having `dolfinx/foo` that doesn't have dolfin.

**Comment by jhale** [comment]
Don't really agree. The Dockerfiles for test-env and dev-env are similar, so they could be merged. But the concrete versions of those images (particularly, the PETSc ARCH and the compiler options) are quite different. 

Two options:

1. Merge the Dockerfiles and use arguments at build time to produce the two concrete images (one for testing dolfinx, one for nightly builds aimed at end users, or at people wishing to build a performant version).

2. Build a full selection of PETSc/SLEPc ARCHs in one 'does it all' image.

**Comment by garth-wells** [comment]
Let me expand my point - why do we need `dolfinx/dev-env` when we have `dolfinx/dolfinx`? The latter contains the former.

**Comment by jhale** [comment]
Ah, I see. Because it's clean. The use case is I want to bring in my own branches of FEniCS Project components and build them against a performant and well setup set of dependencies.

**Comment by garth-wells** [comment]
I would suggest installing the 'real' version into `/usr/local/dolfinx-real` to avoid files in the system location possibly being picked up when in complex mode.

On the point of a 'clean' image, if the DOLFIN builds are out of the system paths is the issue then the install of the FEniCS Python modules in a system location?

**Comment by jhale** [comment]
Can do that. I will make the default `ENV` point at the real version which is likely to be by far the most commonly used, and the script will then override to complex mode.

Yes, the issue is it is 'non-trivial' to both install and run DOLFINX and it's Python components outside of the standard paths. You wouldn't want to have to remember the technicalities if you just wanted to bring up a reasonable environment and install some custom branches. It is nice just to be able to install into the default paths.

**Comment by garth-wells** [comment]
Related issue: #970

**Pull request merged**
