### PR TITLE
Fixes to `Timer` logic

### PR DESCRIPTION
**Pull request by garth-wells**
The logic behind the interaction between `Timer` and `TimeLogger` was messed up. This attempts to fix it without interface changes.

Improves and fixes tests.

### CODE REVIEW

**Comment by jorgensd** [comment]
Shouldn't "stop" imply a "flush" if we want to maintain the timing API?

There isn't a way to "pause" a timer, as "start" resets the accumulated time. Thus stop should imply flush.

**Comment by garth-wells** [comment]
> Shouldn't "stop" imply a "flush" if we want to maintain the timing API?
> 

The logic has always been that durations are logged with the Timer is destroyed. `flush` forces this to happen earlier. 

> There isn't a way to "pause" a timer, as "start" resets the accumulated time. Thus stop should imply flush.

There was a `resume` - @schnellerhase removed it because it was untested. I could now be added back (I think it should).

**Comment by garth-wells** [comment]
The Python wrappers could call `stop` and `flush`.

**Comment by schnellerhase** [comment]
> There was a `resume` - @schnellerhase removed it because it was untested. I could now be added back (I think it should).

This also allowed for one less state to manage in the Timer and thus simpler logic. I think keeping the states to a minimum is best here.

What do we need the `resume/restart` functionality for? Together with the `TimeLogger` I think we can do without.

**Comment by jorgensd** [comment]
> > There was a `resume` - @schnellerhase removed it because it was untested. I could now be added back (I think it should).
> 
> This also allowed for one less state to manage in the Timer and thus simpler logic. I think keeping the states to a minimum is best here.
> 
> What do we need the `resume/restart` functionality for? Together with the `TimeLogger` I think we can do without.

If we use the `TimeLogger` for resuming timings, then stop should definitely flush, as there is no clear benefit of keeping the object around then?

**Comment by garth-wells** [comment]
> > > There was a `resume` - @schnellerhase removed it because it was untested. I could now be added back (I think it should).
> > 
> > 
> > This also allowed for one less state to manage in the Timer and thus simpler logic. I think keeping the states to a minimum is best here.
> > What do we need the `resume/restart` functionality for? Together with the `TimeLogger` I think we can do without.
> 
> If we use the `TimeLogger` for resuming timings, then stop should definitely flush, as there is no clear benefit of keeping the object around then?

There are users who use stop/resume. It wasn't covered by tests (it is now), but that doesn't mean it's not used.

Timings should only be logged to when finished (by the destructor, or when manually flushed), otherwise the counter get messed up.

**Pull request merged**
