### PR TITLE
Make `Function` not inherit `GenericFunction`

### PR DESCRIPTION
**Pull request by michalhabera**
Supports #183 .

This PR makes `Function` again fully fledged independent class.
It also disables usage of Function as GenericFunction.

I redefined what could be attached as coefficient to a form. Now only `Function` is allowed, i.e. the true finite element function. This temporarily disables use of `Constant` and `Expression` in forms, however I replaced constant with scalar values for time being.

Since `Constant` and `Expression` are children of `GenericFunction`, they can still be used in interpolation and boundary conditions.

Ad `Expression`: each use of expression in tests could have been (and I did so) replaced with its true UFL equivalent. This is **the exact** representation at quadrature points. I had to redefine reference norms in tests.

I changed `Poisson.ufl` and its `main.cpp` such that no `Expression` is used. Again, Source term and flux term could be **exactly** replaced in .ufl file usign UFL primitives.

### CODE REVIEW

**Comment by michalhabera** [comment]
Tests are green finally.

**Comment by garth-wells** [comment]
This has some major interface changes and some loss of functionality that need to be discussed in detail. 

I think the existing high level interface for forms is pretty good, so changes should be made with caution. It would be best to sketch out a design proposal as a 'Project' (https://github.com/FEniCS/dolfinx/projects)

**Comment by michalhabera** [comment]
Sure I will do so.

This is not really changing user high level interface. It only makes underlying concepts clearer. But dont be afraid to totally discard it, I am ok with it ;)

**Comment by garth-wells** [comment]
As agreed in discussion, this change will be broken down into small steps with separate pull request.

**Pull request closed without merging**
