### PR TITLE
Improvements to `demo_helmholtz.py` and  `demo_scattering_boundary_conditions.py`

### PR DESCRIPTION
**Pull request by BillMaZengou**
Delete an unused variable in demo_helmholtz.py
Add a description for clarity in demo_scattering_boundary_conditions.py

### CODE REVIEW

**Comment by francesco-ballarin** [comment]
@BillMaZengou please have a look at GitHub actions status that you see below your message, for instance https://github.com/FEniCS/dolfinx/actions/runs/7551811797/job/20559652794?pr=2992.

You'll find that they are failing because of a `flake8` check: try to fix the whitespace issue and add a new commit with your change.

**Comment by BillMaZengou** [comment]
Yes. Sorry for that. The white space was not clear in my IDE. 
I found a way to delete it. However, I am not sure how to push the change again in this PR...

**Comment by BillMaZengou** [comment]
> @BillMaZengou please have a look at GitHub actions status that you see below your message, for instance https://github.com/FEniCS/dolfinx/actions/runs/7551811797/job/20559652794?pr=2992.
> 
> You'll find that they are failing because of a `flake8` check: try to fix the whitespace issue and add a new commit with your change.

It seems that it is automatically updated. 

Briefly document my steps for future reference (as it is quite difficult to notice whitespace in some IDEs, e.g. Jupyter): 
- `pip install pylint` or `pip install flake8` to install 
- `pylint <file>` or `flask8 <file>` for checking the format issue
- add `nnoremap <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>` in `~/.vimrc` 
- open file with vim and solve the whitespace issue by simply pressing F5 key

[https://vi.stackexchange.com/questions/454/whats-the-simplest-way-to-strip-trailing-whitespace-from-all-lines-in-a-file](url)

**Review by jorgensd — APPROVED** [review]

**Comment by BillMaZengou** [comment]
> Thanks @BillMaZengou, this has now been queued for merge by @jorgensd . We may be switching soon to `ruff` for formatting (instead of `flake8`), so you may have to slightly change the steps in the first two bullets at some point in the future.

Thanks! I will research the format. I did not pay attention to those format before. It has been a good practice for me

**Pull request merged**
