### PR TITLE
Add KaHIP interface for mesh partitioning 

### PR DESCRIPTION
**Pull request by IgorBaratta**
- Create FIndKaHIP file to link KaHIP.
   - test the interface in serial
- Define KaHIP as an optional package
- Create the dolfin KaHIP interface 
- Add option to use the new interface  in `Partitioning.h`

### CODE REVIEW

**Comment by garth-wells** [comment]
@IgorBaratta Could you generate some timing data for partitioning with KaHIP when the code is ready, but before merging? We can help with access to machines to test at large process counts if you need it.

**Comment by IgorBaratta** [comment]
> @IgorBaratta Could you generate some timing data for partitioning with KaHIP when the code is ready, but before merging? We can help with access to machines to test at large process counts if you need it.

@garth-wells, sure, I can generate the timing. And I could definitely use some help to access some machines for testing.
I believe the machines I currently have access to are not particularly helpful for this task.

**Comment by chrisrichardson** [comment]
@garth-wells - I think the timing results: 
 https://gist.github.com/IgorBaratta/038747f9aff44eb844c0913614bf0c03
are good enough that it is worth merging.

**Comment by IgorBaratta** [comment]
I'm working on some tests on the branch [partition-py](https://github.com/FEniCS/dolfinx/tree/igor/partition-py) which will make easier to test this PR. And then i'll change the status to  "Ready for Review".

**Comment by IgorBaratta** [comment]
No. It was installed directly on circleci (config.yml) for testing.
Should I add it to the Dockerfile?

**Comment by garth-wells** [comment]
I think adding it to the Dockerfile would be good. It will get plenty of local testing with KaHIP installed, so best to have some testing of it on CircleCI.

**Comment by IgorBaratta** [comment]
PR [#42](https://github.com/schulzchristian/KaHIP/pull/42) needs to be merged first.

**Comment by jhale** [comment]
Could you pin the kahip pull against a particular version or even commit hash in the Dockerfile? Use the same strategy as an environment variable for the other packages.

**Comment by IgorBaratta** [comment]
> Could you pin the kahip pull against a particular version or even commit hash in the Dockerfile? Use the same strategy as an environment variable for the other packages.

Good point. Probably better against a commit hash. But the other PR has to be landed first.

**Comment by IgorBaratta** [comment]
KaHIP PR has been merged.
The kahip pull points to the commit  14be06c,  (make OpenMP an optional dependency for KaHIP).

I think it can be merged? @chrisrichardson @garth-wells

**Pull request merged**
