### PR TITLE
Add UI for XDMF mixed topologies

### PR DESCRIPTION
**Pull request by jorgensd**
See details about the input data in #1156 

This PR adds the possibility of selecting with topological dimension of a XDMFTopology of typed "mixed" one should extract. Default behavior will be to extract the topology with highest topological dimension.

Similar features added for reading in meshtags.

Note that all data is read on the first processor, then distributed later on, as there is no reasonable way of partitioning the cell_topology or cell_values a priori.

### CODE REVIEW

**Comment by michalhabera** [comment]
If this PR makes reading the entire topology on the rank0 processor, that is surely wrong.

What do you mean, "no reasonable way of partitioning cell_topology"? Do you mean partitioning the HDF file to select a chunk that should be read? This could be achieved by reading a chunk of size which is a multiple of the least common multiple of topology sizes of all cell types.

**Comment by jorgensd** [comment]
> If this PR makes reading the entire topology on the rank0 processor, that is surely wrong.
> 
> What do you mean, "no reasonable way of partitioning cell_topology"? Do you mean partitioning the HDF file to select a chunk that should be read? This could be achieved by reading a chunk of size which is a multiple of the least common multiple of topology sizes of all cell types.

As PolyLine has an unbounded number of nodes in the topology (defined by the second argument), there is no common multiple. If we assume PolyLine always has 2 nodes (being first order), we can find the least common multiple. We can have an asset for such types.

**Comment by garth-wells** [comment]
This is a non-starter if all data is read on one rank.

**Comment by jorgensd** [comment]
Closed due to out of data and soon to be deprecated (xdmf) format

**Pull request closed without merging**
