### PR TITLE
Updates for Doxygen 1.9.5

### PR DESCRIPTION
**Pull request by chrisrichardson**
* Update Doxyfile
* Add some fixes for sphinx

### CODE REVIEW

**Comment by jorgensd** [comment]
I get some issues building the docs locally:
```c++
/root/shared/dolfinx/cpp/doc/source/fem.rst:64: WARNING: Parsing of expression failed. Using fallback parser. Error was:
Error in postfix expression, expected primary expression or type.
If primary expression:
  Invalid C++ declaration: Expected identifier in nested name. [error at 205]
    std::pair< DofMap, std::vector< std::int32_t > > collapse (MPI_Comm comm, const mesh::Topology &topology, const std::function< std::vector< int >(const graph::AdjacencyList< std::int32_t > &)> &reorder_fn=[](const graph::AdjacencyList< std::int32_t > &g) { return graph::reorder_gps(g);}) const
    -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^
If type:
  Invalid C++ declaration: Expected identifier in nested name. [error at 205]
    std::pair< DofMap, std::vector< std::int32_t > > collapse (MPI_Comm comm, const mesh::Topology &topology, const std::function< std::vector< int >(const graph::AdjacencyList< std::int32_t > &)> &reorder_fn=[](const graph::AdjacencyList< std::int32_t > &g) { return graph::reorder_gps(g);}) const
    -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^
```
related to https://github.com/FEniCS/dolfinx/blob/chris/doxygen/cpp/dolfinx/fem/DofMap.h#L144-L146
can you reproduce.
These issues only happen with the latest sphinx 5.3.0, not with 5.02 which we have pinned to on CI

**Comment by jorgensd** [comment]
Probably related to https://github.com/sphinx-doc/sphinx/issues/10152

**Review by jorgensd — APPROVED** [review]
Looks good. See general comment regarding sphinx

**Comment by chrisrichardson** [comment]
I have the same warning with sphinx - but the docs still seem to build OK.

**Pull request merged**
