### PR TITLE
Dockerfile PETSc version bump

### PR DESCRIPTION
**Pull request by garth-wells**
Also add PETSc garbage collection to tests.

### CODE REVIEW

**Comment by jorgensd** [comment]
Are you sure about this? We downgraded due to the various issues listed in: https://github.com/FEniCS/dolfinx/pull/2483
Are all of then resolved ?

**Comment by garth-wells** [comment]
> Are you sure about this? We downgraded due to the various issues listed in: #2483 Are all of them resolved ?

`PETSc.garbage_cleanup()` has been added. See https://gitlab.com/petsc/petsc/-/issues/1309.

**Comment by jorgensd** [comment]
> > Are you sure about this? We downgraded due to the various issues listed in: #2483 Are all of them resolved ?
> 
> `PETSc.garbage_cleanup()` has been added. See https://gitlab.com/petsc/petsc/-/issues/1309.

But have they merged in the fix for https://gitlab.com/petsc/petsc/-/issues/1288
into a release?

**Comment by garth-wells** [comment]
Tested inside Docker locally. Seems ok with latest MPI releases.

**Comment by francesco-ballarin** [comment]
Are we sure that all issues are solved?

I have heavily parametrized tests in multiphenicsx 
https://github.com/multiphenics/multiphenicsx/blob/update/tests/unit/fem/test_assembler_restriction.py
and I am still getting failures like
```
internal_Dist_graph_create_adjacent(125).: MPI_Dist_graph_create_adjacent(comm=0xc40013e0, indegree=0, sources=(nil), sourceweights=0x7f5eeba42af4, outdegree=0, destinations=(nil), destweights=0x7f5eeba42af4, MPI_INFO_NULL, reorder=0, comm_dist_graph=0x7ffde86a6b08) failed
MPIR_Dist_graph_create_adjacent_impl(319): 
MPII_Comm_copy(913)......................: 
MPIR_Get_contextid_sparse_group(591).....: Too many communicators (0/2048 free on this process; ignore_id=0)
Abort(71919887) on node 0 (rank 0 in comm 368): application called MPI_Abort(comm=0xC40013E0, 71919887) - process 0
```

I am quite confident the error is not with my code, since:
* by installing `pytest-repeat` I can see the failed test moving to a different parameterization value depending on the value of `--count`.
* tests run ok on my local machine (with openmpi, rather than mpich)

**Pull request merged**
