### PR TITLE
pass PYTHON_EXECUTABLE as well as Python3_EXECUTALBE from setup.py to make

### PR DESCRIPTION
**Pull request by js947**
The pybind11 CMake module reads PYTHON_EXECUTABLE and the PETSc4py CMake module reads Python3_EXECUTABLE. We should specify both to avoid potential problems of having two different pythons in the same build.

### CODE REVIEW

**Comment by jhale** [comment]
Could you add a comment? We'll never remember this in two years!

**Comment by js947** [comment]
CMake will probably change everything in 2 years ;-) but I take your point, comment added.

**Comment by garth-wells** [comment]
What is the recommend variable name - `PYTHON_EXECUTABLE` or `Python3_EXECUTABLE`? DOLFIN provides `FindMPI4PY.cmake` and `FindPETSc4py.cmake` so these we can easily change.

**Comment by js947** [comment]
I think Python3_EXECUTABLE is the more normal one. It is what you get from FindPython3. 

PYTHON_EXECUTABLE is required by the pybind11 modules, which come with the pybind11 install. Specifically the FindPythonLibsNew.cmake file which looks like it might be a shim from quite some time ago.

**Pull request merged**
