### PR TITLE
Remove constant from hyperelasticity ufl

### PR DESCRIPTION
**Pull request by jorgensd**
As described in the comments of the PR, we have to carefully introduce dolfinx.Constant to the users, as it should only be used in specific cases, which will vary in the C++ and python layer.

### CODE REVIEW

**Review by chrisrichardson — APPROVED** [review]

**Comment by garth-wells** [comment]
I there a particular motivation for this change?

**Comment by jorgensd** [comment]
> I there a particular motivation for this change?

As you can in the diff, there was commented code with constant usage (probably from prior to dolfinx::Constant existing. So I figured it is nice to highlight that one can and should use constants, also in C++

**Comment by michalhabera** [comment]
In principle, we should only use `Constant` in places, where user changes the value of it. Or explicitly state this is the intention. We had `Constant` all over in old-FEniCS code and users inherited this from our demos and examples, just putting Constant() around any "constant" value in their forms.
Constant is not recommended for performance reasons as it 1. increases the amount of data that has to be pre-fetched and passed to kernel and 2. is a black-box object for form compiler, so `Constant(2.0) + Constant(1.0)` is computed at each cell, while `2.0 + 1.0` would be evaluated immediately to `3.0` by UFL.

**Comment by jorgensd** [comment]
> In principle, we should only use `Constant` in places, where user changes the value of it. Or explicitly state this is the intention. We had `Constant` all over in old-FEniCS code and users inherited this from our demos and examples, just putting Constant() around any "constant" value in their forms.
> 
> Constant is not recommended for performance reasons as it 1. increases the amount of data that has to be pre-fetched and passed to kernel and 2. is a black-box object for form compiler, so `Constant(2.0) + Constant(1.0)` is computed at each cell, while `2.0 + 1.0` would be evaluated immediately to `3.0` by UFL.

Isn't wrapping E and nu and not lambda and mu exactly enforcing that principle?
These are the two parameters a user would vary in this demo?

**Comment by garth-wells** [comment]
`Constant` (constant in space) is intended for cases where it changes during a simulation, e.g. time `t`, or is not known at compile time, e.g. in a library with precompiled forms or a problem involving a sweep over numerous values of the constants.

**Comment by jorgensd** [comment]
> `Constant` (constant in space) is intended for cases where it changes during a simulation, e.g. time `t`, or is not known at compile time, e.g. in a library with precompiled forms or a problem involving a sweep over numerous values of the constants.

So we have two options then:
1. close this PR as the parameters are known at compilation time
2. Change this PR to remove the commented lines relating to constant in the ufl file.

**Comment by michalhabera** [comment]
With this state of demo I'd vote for 2., just remove the commented `Constant`. If you want to keep the `Constant` then demo must make use of it, either change its value and assemble two problems, or very strongly advertise this.

**Pull request merged**
