### PR TITLE
Wrap dolfin.generation module

### PR DESCRIPTION
**Pull request by michalhabera**
Another bunch of python wrappers. Calling `dolfin.cpp.generation` should be avoided in user code from now on.

### CODE REVIEW

**Comment by garth-wells** [comment]
Looks good.

I'm wondering if `BoxMesh`, etc, look like a class rather than a function that return a `Mesh`?

**Comment by michalhabera** [comment]
On cpp side its a class with static-only methods. Looks like a namespace to me. I tried to keep it simple and not create python class for such trivial state-less object.

**Comment by garth-wells** [comment]
@michalhabera we definitely don't want a class - just wondering if we need 'create' in the name, and whether we should use lower-case.

**Comment by michalhabera** [comment]
I don't see "create" in the name. 
Lower-case names: `interval_mesh`, `unit_square_mesh` etc would be more appropriate, but `UnitSquareMesh` is pretty rooted in users minds.

If you want just lower-cased namespaced methods (similar to what is in assembler) I can change both c++ and python sides. I would do it in separate PR if you agree.

**Comment by michalhabera** [comment]
@garth-wells I think this is OK for public interface. Happy to have it merged.

**Pull request merged**
