### PR TITLE
Take tabulate signature from ufc.h

### PR DESCRIPTION
**Pull request by michalhabera**
Based on https://github.com/FEniCS/ffcx/pull/155

### CODE REVIEW

**Comment by chrisrichardson** [comment]
While we are here, can we standardise on either `kernel` or `fn` in the assemblers? It is confusing to have a mixture.

**Comment by michalhabera** [comment]
I agree, it became visible just now, when obscure type is shortcut :) I don't have any opinion which is better.

**Comment by chrisrichardson** [comment]
Maybe we could also consider Issue #555 - and change the interface to `register_tabulate_tensor` to use a `std::function`?

**Comment by chrisrichardson** [comment]
> I agree, it became visible just now, when obscure type is shortcut :) I don't have any opinion which is better.

I guess `kernel` says more. `fn` is pretty meaningless.

**Comment by michalhabera** [comment]
@chrisrichardson Renamed and addressed #555 . Only `std::function` is in our interfaces.

**Comment by mrambausek** [comment]
Thanks for considering my suggestion in #555 ! Btw. is there a reason why only cell integrals can be set but no facet integrals?

**Comment by michalhabera** [comment]
@mrambausek Just a missing setter. But we will most likely reorganise these setters a bit, there are currently 2 ways of setting tabulation kernel -- via Form and via FormIntegrals, it should be preferably just in one place.

**Comment by michalhabera** [comment]
I guess I will cherry-pick set/get kernel methods name unification as a separate PR.

**Pull request closed without merging**
