### PR TITLE
Add complex wrappers for equivalent floating type for exposed dof transformations

### PR DESCRIPTION
**Pull request by jorgensd**
Required for: https://github.com/jorgensd/adios4dolfinx/pull/32

### CODE REVIEW

**Review by garth-wells — APPROVED** [review]

**Comment by garth-wells** [comment]
We probably want to add 'vectorised' versions of these functions if they're used for something other than small-scale testing.

**Comment by jorgensd** [comment]
> We probably want to add 'vectorised' versions of these functions if they're used for something other than small-scale testing.

What do you imply by vectorized here?
You can use the `dim` argument to apply the transformation to loads of data, given that it is batched by the `permutation_index`. (https://github.com/FEniCS/dolfinx/blob/ca09b5d48de34cd0373d50ac0803696653483832/cpp/dolfinx/fem/FiniteElement.h#L527-L535). I'm not sure why we call it dim in the pybinding and block_size everywhere else.

**Comment by jorgensd** [comment]
> We probably want to add 'vectorised' versions of these functions if they're used for something other than small-scale testing.

They are used in my checkpointing/input-output library, which is currently the only way of saving/loading `dolfinx.fem.Function` based on any finite element in DOLFINx, so I guess it is not only used in small-scale testing.

**Review by IgorBaratta — APPROVED** [review]

**Comment by garth-wells** [comment]
> > We probably want to add 'vectorised' versions of these functions if they're used for something other than small-scale testing.
> 
> What do you imply by vectorized here? 

Process data for more than one cell at a time.

**Pull request merged**
