### PR TITLE
Compatibility with pygmsh 7.0.0

### PR DESCRIPTION
**Pull request by francesco-ballarin**
See https://github.com/nschloe/pygmsh/commit/62516e7186af53ed5c8b02deb9a9876d79c6f0f9

### CODE REVIEW

**Comment by francesco-ballarin** [comment]
@jhale The `fenicsproject/test-env:openmpi` container seems to be out of date. Do we need to run a manual trigger? (however, that job seems to be skipped in the last two manual runs)

**Comment by jorgensd** [comment]
> See https://github.com/nschloe/pygmsh/commit/62516e7186af53ed5c8b02deb9a9876d79c6f0f9

There is alot more changes in this Version bump than just renaming the module. Did you try running: https://github.com/FEniCS/dolfinx/blob/master/python/demo/gmsh/demo_gmsh.py
I am currently working removing all traces of pygmsh from dolfinx, using the Gmsh Python API, similar to what i proposed in https://github.com/nschloe/pygmsh/issues/373

**Comment by francesco-ballarin** [comment]
Marking as [WIP] because of missing alternative for add_raw_code in pygmsh 7.0.0, see https://github.com/nschloe/pygmsh/issues/373

**Comment by jhale** [comment]
> @jhale The `fenicsproject/test-env:openmpi` container seems to be out of date. Do we need to run a manual trigger? (however, that job seems to be skipped in the last two manual runs)

I didn't notice this before, thanks. I'll check to see why it's skipping just the `openmpi` image build.

**Comment by jhale** [comment]
The openmpi image will be refreshed in about 1 1/2 hours.

**Comment by francesco-ballarin** [comment]
I am closing this, as #1145 will fix the pygmsh compatibility and #1146 has fixed the typo in the docker base image generation

**Pull request closed without merging**
