### PR TITLE
Enable partition of a `box mesh` on subset of processes

### PR DESCRIPTION
**Pull request by IgorBaratta**

### CODE REVIEW

**Review by garth-wells — COMMENTED** [review]
Looks like this only works 'fully' for ParMETIS? Other partitioners partition using all ranks, even if graph is empty on some ranks.

**Comment by IgorBaratta** [comment]
> Looks like this only works 'fully' for ParMETIS? Other partitioners partition using all ranks, even if graph is empty on some ranks.

I'll have a look at it.

**Comment by jorgensd** [comment]
> Looks like this only works 'fully' for ParMETIS? Other partitioners partition using all ranks, even if graph is empty on some ranks.

Wasn't this one of the things that was working with KaHip way back when @IgorBaratta worked on it?

**Comment by garth-wells** [comment]
> Before it was more explicit. Now, if the local graph doesn't contain any nodes, the process is not used for partition.

It's a work-around for ParMETIS, which fails if a rank has no part of the graph.

**Pull request closed without merging**
