### PR TITLE
Cmake-format support

### PR DESCRIPTION
**Pull request by tiagovla**

### CODE REVIEW

**Comment by jorgensd** [comment]
Note that the demo cmake files are generated by https://github.com/FEniCS/dolfinx/blob/main/cpp/cmake/scripts/generate-cmakefiles.py
So these strings should be modified to adhere to cmake-format

**Comment by jhale** [comment]
I quite like it. Would also be good to have this added as a non-blocking step in the CI.

**Review by garth-wells — DISMISSED** [review]
See the comment in https://github.com/FEniCS/dolfinx/pull/2431#issuecomment-1301319271.

**Comment by jhale** [comment]
Can you make sure that cmakelang gets put into the Dockerfile so it can be subsequently tidied up in the GitHub action after the merge (one day!).

**Review by jhale — APPROVED** [review]

**Pull request merged**
