### PR TITLE
Added unstructured unit meshes for testing

### PR DESCRIPTION
**Pull request by jorgensd**
Helpful for dof permuting tests, and could probably be used in pipline as well.
Generated with the following script:
```
import pygmsh
import meshio
def UnitSquareMesh(celltype, N=3):

    geom = pygmsh.opencascade.Geometry()
    rectangle = geom.add_rectangle([0, 0, 0], 1, 1, char_length=1/N)
    if celltype =="quad":
        geom.add_raw_code("Recombine Surface {:};")
        geom.add_raw_code("Mesh.RecombinationAlgorithm = 2;")
    mesh = pygmsh.generate_mesh(geom, verbose=False)

    mesh.prune()
    mesh = meshio.Mesh(points=mesh.points, cells={celltype: mesh.cells[celltype]})

    meshio.write("UnitSquareMesh_{0:s}.xdmf".format(celltype), mesh, file_format="xdmf-xml")


def UnitCubeMesh(celltype, N=3):

    geom = pygmsh.opencascade.Geometry()
    rectangle = geom.add_rectangle([0, 0, 0], 1, 1, char_length=1/N)
    if celltype =="hexahedron":
        geom.add_raw_code("Mesh.RecombinationAlgorithm = 2;")
        geom.add_raw_code("Recombine Surface {:};")
    recombine = True if celltype == "hexahedron" else False
    geom.extrude(rectangle, translation_axis=[0, 0, 1], num_layers=N, recombine=recombine)

    mesh = pygmsh.generate_mesh(geom, verbose=True, geo_filename=celltype+".geo")
    mesh = meshio.Mesh(points=mesh.points, cells={celltype: mesh.cells[celltype]})
    meshio.write("UnitCubeMesh_{0:s}.xdmf".format(celltype), mesh, file_format="xdmf-xml")

UnitSquareMesh("triangle")
UnitSquareMesh("quad")


UnitCubeMesh("tetra")
UnitCubeMesh("hexahedron")
```

### CODE REVIEW

**Comment by garth-wells** [comment]
The mesh files seem to be unused in the tests.

**Comment by mscroggs** [comment]
I believe they are. I think it may make sense to merge this into my vector dof branch where we need these meshes to improve the testing

**Comment by garth-wells** [comment]
I couldn't see any of the newly added files appearing in a `test_foo.py` file in the PR?

**Comment by jorgensd** [comment]
> I couldn't see any of the newly added files appearing in a `test_foo.py` file in the PR?

I'll replace the built-in meshes in pipeline tests

**Comment by jorgensd** [comment]
@garth-wells Replaced built-in meshes with unstructured versions. Removed the unitinterval tests as I havent generated a 1D mesh.

**Comment by mscroggs** [comment]
When this is merged, can we close https://github.com/FEniCS/dolfinx/issues/332?

**Comment by jorgensd** [comment]
> When this is merged, can we close #332?

I would say together with  #674 , as it checks some higher order properties .

**Pull request merged**
