### PR TITLE
Try setting solver for dp_simplex

### PR DESCRIPTION
**Pull request by jorgensd**
Debug for #3179

### CODE REVIEW

**Comment by minrk** [comment]
fwiw, the mumps version worked (a113d7b5c444fcf1112a04799ce09ec6744ce7b1) not petsc, haven't tried cg jacobi

**Comment by minrk** [comment]
fwiw, the mumps version worked (a113d7b5c444fcf1112a04799ce09ec6744ce7b1) not petsc, haven't tried cg jacobi

**Comment by minrk** [comment]
confirmed this fixes #3179: https://github.com/conda-forge/fenics-dolfinx-feedstock/pull/72

**Comment by garth-wells** [comment]
PR #3184 changes the solver to a build-in rather than PETSc solver, and adjusts tolerances for different scalar types.

**Comment by jorgensd** [comment]
> PR #3184 changes the solver to a build-in rather than PETSc solver, and adjusts tolerances for different scalar types.

This PR was never meant for merging, but to Give Min an easy way to test different solvers to diagnose the conda issue.

**Pull request closed without merging**
