### PR TITLE
Switch boost::filesystem to std::filesystem

### PR DESCRIPTION
**Pull request by garth-wells**
We didn't do this in the past because gcc prior to 9.1 and clang/llvm prior to 9.0 required explicit linking to the 'filesystem' library (see Notes section at https://en.cppreference.com/w/cpp/filesystem). 

See also #1978.

### CODE REVIEW

**Comment by michalhabera** [comment]
Some issues we had in past with std::filesystem were similar to concatenation bug addressed in https://github.com/FEniCS/dolfinx/pull/1826, so it should be safe now.

**Review by michalhabera — APPROVED** [review]

**Review by francesco-ballarin — APPROVED** [review]

**Comment by drew-parsons** [comment]
It applies cleanly enough to 0.3.0.  I'll run it past the debian build daemons.

**Comment by drew-parsons** [comment]
I'm getting a segfault in C++ unittests. Would this be expected if the patch is applied to 0.3.0?

It's happening in the xdmf code

Error message is:
```
/projects/fenics/build/fenics-dolfinx/obj-x86_64-linux-gnu-real/runtests-unit-real$ ./unittests 
2022-02-02 12:14:19.499 (   3.411s) [        98946BC0]              utils.cpp:518   INFO| Compute partition of cells across ranks
2022-02-02 12:14:19.499 (   3.411s) [        98946BC0]         graphbuild.cpp:550   INFO| Build mesh dual graph
2022-02-02 12:14:19.499 (   3.411s) [        98946BC0]         graphbuild.cpp:308   INFO| Build local part of mesh dual graph
2022-02-02 12:14:19.499 (   3.412s) [        98946BC0]         graphbuild.cpp:48    INFO| Build nonlocal part of mesh dual graph
2022-02-02 12:14:19.499 (   3.412s) [        98946BC0]         graphbuild.cpp:562   INFO| Graph edges (local:80, non-local:0)
2022-02-02 12:14:19.500 (   3.412s) [        98946BC0]             scotch.cpp:117   INFO| Compute graph partition using PT-SCOTCH
2022-02-02 12:14:19.500 (   3.412s) [        98946BC0]         graphbuild.cpp:308   INFO| Build local part of mesh dual graph
2022-02-02 12:14:19.500 (   3.413s) [        98946BC0]           Topology.cpp:299   INFO| Create topology
2022-02-02 12:14:19.500 (   3.413s) [        98946BC0]          partition.cpp:175   INFO| Compute ghost indices
2022-02-02 12:14:19.502 (   3.415s) [        98946BC0]           XDMFFile.cpp:110   INFO| Opened HDF5 file with id "72057594037927936"
2022-02-02 12:14:19.503 (   3.415s) [        98946BC0]          xdmf_mesh.cpp:203   INFO| Adding mesh to node "/Xdmf/Domain"
2022-02-02 12:14:19.503 (   3.415s) [        98946BC0]          xdmf_mesh.cpp:25    INFO| Adding topology data to node "/Xdmf/Domain/Grid"
2022-02-02 12:14:19.505 (   3.417s) [        98946BC0]          xdmf_mesh.cpp:152   INFO| Adding geometry data to node "/Xdmf/Domain/Grid"
2022-02-02 12:14:19.506 (   3.418s) [        98946BC0]           XDMFFile.cpp:110   INFO| Opened HDF5 file with id "72057594037927937"
2022-02-02 12:14:19.506 (   3.418s) [        98946BC0]           XDMFFile.cpp:257   INFO| Read topology data "mesh" at "/Xdmf/Domain"

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unittests is a Catch v2.13.7 host application.
Run with -? for options

-------------------------------------------------------------------------------
Distributed Mesh
  SCOTCH
-------------------------------------------------------------------------------
./obj-x86_64-linux-gnu-real/test/unit/mesh/distributed_mesh.cpp:121
...............................................................................

./obj-x86_64-linux-gnu-real/test/unit/mesh/distributed_mesh.cpp:121: FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

===============================================================================
test cases:     8 |     7 passed | 1 failed
assertions: 11141 | 11140 passed | 1 failed

[sandy:236673] *** Process received signal ***
[sandy:236673] Signal: Segmentation fault (11)
[sandy:236673] Signal code:  (-6)
[sandy:236673] Failing at address: 0x3e800039c81
[sandy:236673] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x13200)[0x7f509fcc6200]
[sandy:236673] [ 1] /lib/x86_64-linux-gnu/libc.so.6(+0x161394)[0x7f509fc4c394]
[sandy:236673] [ 2] /home/drew/projects/fenics/build/fenics-dolfinx/debian/tmp-real/usr/lib/x86_64-linux-gnu/libdolfinx_real.so.0.3(+0x19b106)[0x7f50a198a106]
[sandy:236673] [ 3] /home/drew/projects/fenics/build/fenics-dolfinx/debian/tmp-real/usr/lib/x86_64-linux-gnu/libdolfinx_real.so.0.3(_ZN7dolfinx2io10xdmf_utils14get_hdf5_pathsB5cxx11ERKN4pugi8xml_nodeE+0xa8a)[0x7f50a1991a0a]
[sandy:236673] [ 4] /home/drew/projects/fenics/build/fenics-dolfinx/debian/tmp-real/usr/lib/x86_64-linux-gnu/libdolfinx_real.so.0.3(_ZN7dolfinx2io9xdmf_read11get_datasetIlEESt6vectorIT_SaIS4_EEP19ompi_communicator_tRKN4pugi8xml_nodeElSt5arrayIlLm2EE+0x1f9)[0x7f50a1988589]
[sandy:236673] [ 5] /home/drew/projects/fenics/build/fenics-dolfinx/debian/tmp-real/usr/lib/x86_64-linux-gnu/libdolfinx_real.so.0.3(_ZN7dolfinx2io9xdmf_mesh18read_topology_dataEP19ompi_communicator_tlRKN4pugi8xml_nodeE+0xbb)[0x7f50a19848fb]
[sandy:236673] [ 6] /home/drew/projects/fenics/build/fenics-dolfinx/debian/tmp-real/usr/lib/x86_64-linux-gnu/libdolfinx_real.so.0.3(_ZNK7dolfinx2io8XDMFFile18read_topology_dataENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_+0x395)[0x7f50a1971195]
[sandy:236673] [ 7] ./unittests(+0x97e2c)[0x555d74460e2c]
[sandy:236673] [ 8] ./unittests(+0x9ab8e)[0x555d74463b8e]
[sandy:236673] [ 9] ./unittests(+0x33f4d)[0x555d743fcf4d]
[sandy:236673] [10] ./unittests(+0x50e70)[0x555d74419e70]
[sandy:236673] [11] ./unittests(+0x5b714)[0x555d74424714]
[sandy:236673] [12] ./unittests(+0x5e6fd)[0x555d744276fd]
[sandy:236673] [13] ./unittests(+0x5ec28)[0x555d74427c28]
[sandy:236673] [14] ./unittests(+0x2b6fc)[0x555d743f46fc]
[sandy:236673] [15] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xcd)[0x7f509fb127ed]
[sandy:236673] [16] ./unittests(+0x2c1ea)[0x555d743f51ea]
[sandy:236673] *** End of error message ***
Segmentation fault
```

gdb backtrace is
```
Thread 1 "unittests" received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:443
443	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:443
#1  0x00007ffff7f1a106 in std::char_traits<char>::copy (__n=1617, __s2=0x30 <error: Cannot access memory at address 0x30>, __s1=<optimized out>) at /usr/include/c++/11/bits/char_traits.h:437
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy (__n=1617, __s=0x30 <error: Cannot access memory at address 0x30>, __d=<optimized out>) at /usr/include/c++/11/bits/basic_string.h:359
#3  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy (__n=1617, __s=0x30 <error: Cannot access memory at address 0x30>, __d=<optimized out>) at /usr/include/c++/11/bits/basic_string.h:354
#4  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy_chars (__k2=<optimized out>, __k1=0x30 <error: Cannot access memory at address 0x30>, __p=<optimized out>) at /usr/include/c++/11/bits/basic_string.h:401
#5  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*> (this=this@entry=0x7fffffffc490, __beg=0x30 <error: Cannot access memory at address 0x30>, __end=<optimized out>) at /usr/include/c++/11/bits/basic_string.tcc:225
#6  0x00007ffff7f21a0a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<char*> (__end=<optimized out>, __beg=<optimized out>, this=0x7fffffffc490) at /usr/include/c++/11/bits/basic_string.h:255
#7  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*> (__end=<optimized out>, __beg=<optimized out>, this=0x7fffffffc490) at /usr/include/c++/11/bits/basic_string.h:274
#8  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (__str=<error: Cannot access memory at address 0x30>, this=0x7fffffffc490) at /usr/include/c++/11/bits/basic_string.h:459
#9  dolfinx::io::xdmf_utils::get_hdf5_paths[abi:cxx11](pugi::xml_node const&) (dataitem_node=...) at ./cpp/dolfinx/io/xdmf_utils.cpp:233
#10 0x00007ffff7f18589 in dolfinx::io::xdmf_read::get_dataset<long> (comm=comm@entry=0x555555b9dce0, dataset_node=..., h5_id=h5_id@entry=72057594037927937, range=...) at ./cpp/dolfinx/io/xdmf_read.h:74
#11 0x00007ffff7f148fb in dolfinx::io::xdmf_mesh::read_topology_data (comm=0x555555b9dce0, h5_id=h5_id@entry=72057594037927937, node=...) at ./cpp/dolfinx/io/xdmf_mesh.cpp:301
#12 0x00007ffff7f01195 in dolfinx::io::XDMFFile::read_topology_data (this=this@entry=0x7fffffffcd30, name="mesh", xpath="/Xdmf/Domain") at ./cpp/dolfinx/io/XDMFFile.cpp:258
#13 0x00005555555ebe2c in (anonymous namespace)::test_distributed_mesh (partitioner=...) at ./obj-x86_64-linux-gnu-real/test/unit/mesh/distributed_mesh.cpp:73
#14 0x00005555555eeb8e in C_A_T_C_H_T_E_S_T_0 () at ./obj-x86_64-linux-gnu-real/test/unit/mesh/distributed_mesh.cpp:123
#15 0x0000555555587f4d in Catch::TestInvokerAsFunction::invoke (this=<optimized out>) at ./obj-x86_64-linux-gnu-real/test/unit/catch/catch.hpp:14321
#16 Catch::TestCase::invoke (this=<optimized out>) at ./obj-x86_64-linux-gnu-real/test/unit/catch/catch.hpp:14160
#17 Catch::RunContext::invokeActiveTestCase (this=0x7fffffffdaf0) at ./obj-x86_64-linux-gnu-real/test/unit/catch/catch.hpp:13020
#18 0x00005555555a4e70 in Catch::RunContext::runCurrentTest (this=0x7fffffffdaf0, redirectedCout="", redirectedCerr=...) at ./obj-x86_64-linux-gnu-real/test/unit/catch/catch.hpp:12993
#19 0x00005555555af714 in Catch::RunContext::runTest (this=0x7fffffffdaf0, testCase=...) at ./obj-x86_64-linux-gnu-real/test/unit/catch/catch.hpp:12754
#20 0x00005555555b26fd in Catch::(anonymous namespace)::TestGroup::execute (this=0x7fffffffdae0) at ./obj-x86_64-linux-gnu-real/test/unit/catch/catch.hpp:13347
#21 Catch::Session::runInternal (this=0x7fffffffdda0) at ./obj-x86_64-linux-gnu-real/test/unit/catch/catch.hpp:13553
#22 0x00005555555b2c28 in Catch::Session::run (this=this@entry=0x7fffffffdda0) at ./obj-x86_64-linux-gnu-real/test/unit/catch/catch.hpp:13509
#23 0x000055555557f6fc in Catch::Session::run<char> (argv=<optimized out>, argc=<optimized out>, this=0x7fffffffdda0) at ./obj-x86_64-linux-gnu-real/test/unit/catch/catch.hpp:13231
#24 Catch::Session::run<char> (argv=<optimized out>, argc=<optimized out>, this=0x7fffffffdda0) at ./obj-x86_64-linux-gnu-real/test/unit/catch/catch.hpp:13226
#25 main (argc=<optimized out>, argv=<optimized out>) at ./obj-x86_64-linux-gnu-real/test/unit/main.cpp:10
```

**Comment by drew-parsons** [comment]
Incidentally l.233 in my local xdmf_utils.cpp is the line
```
  return {{paths[0], paths[1]}};
```

**Comment by garth-wells** [comment]
@drew-parsons I got this locally too (one of the later changes), I think it's fixed now.

**Comment by drew-parsons** [comment]
Revised patch is applying and running fine on Debian builds of 0.3.0.

**Pull request merged**
