### PR TITLE
Remove brew unlink

### PR DESCRIPTION
**Pull request by schnellerhase**
Reverts https://github.com/FEniCS/dolfinx/pull/3530 since the `macos-14-arm64` has now been updated, see https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20241125.556.

### CODE REVIEW

**Comment by schnellerhase** [comment]
That is odd - recent CI run https://github.com/FEniCS/dolfinx/actions/runs/12017307562/job/33499338523 shows it has been update - but here it fails with previous error?

**Comment by schnellerhase** [comment]
Run caught a newer release, by chance?
```
  Image: macos-14-arm64
  Version: 20241125.556
```

which has officially not been released - cool :laughing:

**Comment by jhale** [comment]
It can take a few days for images to roll out.

**Comment by schnellerhase** [comment]
https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20241125.556 has no longer the pre-release flag - maybe it has been rolled out completely now?

**Pull request merged**
