### PR TITLE
Drop setting dl open flags in `dolfinx/__init__.py`

### LINKED ISSUE #2835: Is fiddling with dl open flags still needed in `dolfinx/__init__.py`?
See https://github.com/FEniCS/dolfinx/blob/main/python/dolfinx/__init__.py#L10-L25

`git blame` says it came in 6 years ago when `pybind11` wrappers were first prepared for `dolfin`. 

Around six months ago I realized that this was causing problems on Colab, and have a patch in https://github.com/fem-on-colab/fem-on-colab/blob/main/fenicsx/patches/06-do-not-fiddle-with-dlopenflags-in-dolfinx to drop it when packaging there.

With the wrappers moving from `pybind11` to `nanobind`, now seems a good time to raise this issue.

### PR DESCRIPTION
**Pull request by francesco-ballarin**
Opening this to assess question #2835 on CI

Closes #2835

### CODE REVIEW

**Comment by francesco-ballarin** [comment]
All 20 CI runs were successful. Is there any additional CI workflow that would be useful to test, but should be triggered manually?

**Comment by garth-wells** [comment]
Could you test without 'no-binary' in the pip install of NumPy, see https://github.com/FEniCS/dolfinx/blob/cc47953000ebc1c4617119510f57fe040145ad40/docker/Dockerfile.test-env#L151,

**Comment by francesco-ballarin** [comment]
OK, so there are four scenarios:
1. fiddling with dl open flags in `dolfinx/__init__.py`, and installing `numpy` with `no-binary`: this is current `main` branch, and therefore there is not need to test it here;
2. _not_ fiddling with dl open flags in `dolfinx/__init__.py`, and installing `numpy` with `no-binary`: tested in https://github.com/FEniCS/dolfinx/pull/2836/commits/9f5804d027e1485759c97f2c5fbd634a0b1f352c;
3. fiddling with dl open flags in `dolfinx/__init__.py`, and installing `numpy` _without_ `no-binary`: tested in https://github.com/FEniCS/dolfinx/pull/2836/commits/92a5640c12ae91d4040594b293239b582d94fb14;
4. _not_ fiddling with dl open flags in `dolfinx/__init__.py`, and installing `numpy` _without_ `no-binary`: tested in https://github.com/FEniCS/dolfinx/pull/2836/commits/8f92275d933836a86e87058b8f92bc2925163d8d

All four scenarios are successful on CI, so I would conclude that fiddling with dl open flags in `dolfinx/__init__.py` is not necessary, and that installing `numpy` with `no-binary` is not necessary either.

Todo list after this PR is approved, and before merge:
* [ ] rebase so that https://github.com/FEniCS/dolfinx/pull/2836/commits/9f5804d027e1485759c97f2c5fbd634a0b1f352c and https://github.com/FEniCS/dolfinx/pull/2836/commits/57b03f7513df37c34a0928b77bd73262851fffd9 are kept, and https://github.com/FEniCS/dolfinx/pull/2836/commits/86736432eb077d03962134c9adfc330a685ad06a, https://github.com/FEniCS/dolfinx/pull/2836/commits/92a5640c12ae91d4040594b293239b582d94fb14 and https://github.com/FEniCS/dolfinx/pull/2836/commits/8f92275d933836a86e87058b8f92bc2925163d8d are dropped
* [ ] rerun again https://github.com/FEniCS/dolfinx/actions/workflows/docker-redhat-test-env.yml and https://github.com/FEniCS/dolfinx/actions/workflows/docker-dev-test-env.yml from this branch, but with the default docker tag (rather than the temporary one `pr-2836`)
* [ ] ask @jhale to clean up the temporary docker tags `pr-2836` from the registries (or grant me permissions to do so)
* [ ] ask @drew-parsons and @minrk if they want to test this on ubuntu and conda, respectively?

**Comment by jhale** [comment]
This fix/hack has been in a very long time! I'm relatively persuaded by the above experiments: it's (probably) no longer an issue.

If we get reports of issues we can quickly back it out.

**Comment by jhale** [comment]
Don't worry about conda and debian, my memory is that this is related to numpy binary wheels and blas.

**Review by garth-wells — APPROVED** [review]

**Comment by drew-parsons** [comment]
Agreed about debian.  If it's passing github CI then safe for the purposes of this PR to assume that tests will pass in Debian builds.

**Comment by francesco-ballarin** [comment]
I've carried out 3 of the 4 tasks in my todo list (the remaining one is to clean up the docker repositories together with @jhale). This is now ready to merge.

**Pull request merged**
