### PR TITLE
Raise on DirichletBC in `None` block

### PR DESCRIPTION
**Pull request by michalhabera**
This fixes a potentially dangerous implicit behaviour, where `None` in list of forms for `assemble_matrix_block` ignores all DirichletBC applied there. Typical case: pin pressure in the Stokes problem.

### CODE REVIEW

**Comment by garth-wells** [comment]
This handles the monolithic matrix case - what happens with `MatNest` matrices?

**Comment by michalhabera** [comment]
> This handles the monolithic matrix case - what happens with `MatNest` matrices?

Added the check there as well now.

**Comment by jorgensd** [comment]
@michalhabera  Do you want to fix the merge conflicts on this PR, so that we can get this merged, or should we close it?

**Comment by michalhabera** [comment]
Closing in favour of updated #2142 .

**Pull request closed without merging**
