### PR TITLE
Remove singleton class (SubSystemsManager)

### PR DESCRIPTION
**Pull request by garth-wells**
This removes the rather ugly singleton for initialising and finalising MPI, PETSc, etc from C++. It makes the actions explicit and removes one of the problem areas for multi-threaded applications.

This change is consistent with the C++ interface being explicit. It does not affect the Python interface.

### CODE REVIEW

**Comment by garth-wells** [comment]
We've had this for a long time - the default has been to initialise MPI with threads enabled.

**Comment by chrisrichardson** [comment]
I'd say it's better just to use regular mpi_init, as this is confusing, since we don't use the features.

**Comment by garth-wells** [comment]
We have tests that used threaded assembly (parallel Numba), although in this case `mpi4py` should do the initialisation.

**Comment by chrisrichardson** [comment]
>  MPI_THREAD_MULTIPLE informs MPI that the application is multithreaded, that any thread may issue MPI calls and that different threads may issue MPI calls at the same time.

This is totally beyond anything we need. Even if using threading, we don't issue MPI calls within it. If using threads with no MPI calls, it doesn't need to know about it.

**Comment by garth-wells** [comment]
@chrisrichardson that's not quite true. Using threads requires at least `MPI_THREAD_FUNNELED`.

**Pull request merged**
