### PR TITLE
Remove redundant wrapper

### PR DESCRIPTION
**Pull request by michalhabera**
Importing cpp into python public layer instead. Less code to maintain.

### CODE REVIEW

**Review by jorgensd — APPROVED** [review]
The only issue I see with this is that we suddenly have no documentation of the usage in the Python layer. But that applies to most functions exposed directly through pybind. For instance the last argument in `select_colliding_cells` deserves an docstring.

**Comment by michalhabera** [comment]
I agree, it is a general issue though.

**Comment by jorgensd** [comment]
> I agree, it is a general issue though.

We could maybe use pybind11_mkdoc or Binder? See: https://github.com/pybind/pybind11/issues/1626

**Comment by michalhabera** [comment]
Here is the valid link https://github.com/pybind/pybind11_mkdoc. I would love to see something like this in action.

**Comment by jorgensd** [comment]
> Here is the valid link https://github.com/pybind/pybind11_mkdoc. I would love to see something like this in action.

I had a look at pybind11_mkdoc today. I am not convinced. It is easy to generate the headers, but the parser does not create newlines, thus the doc:
```
  /// Create contact constraint
  ///
  /// @param[in] V The function space
  /// @param[in] slaves List of local slave dofs
  /// @param[in] slaves_cells List of local slave cells
  /// @param[in] offsets Offsets for local slave cells
```
Became:
```
In [3]: mpc.MultiPointConstraint??
Init docstring:
__init__(self: dolfinx_mpc.cpp.mpc.MultiPointConstraint, arg0: dolfinx::function::FunctionSpace, arg1: numpy.ndarray[numpy.int32[m, 1]], arg2: int) -> None

Create contact constraint

@param[in] V The function space @param[in] slaves List of local slave
dofs @param[in] slaves_cells List of local slave cells @param[in]
offsets Offsets for local slave cells
```

**Comment by michalhabera** [comment]
@jorgensd Can you make an issue for better pybind11 docs if doesn't exist? I'd like to merge&close this PR.

**Comment by jorgensd** [comment]
> @jorgensd Can you make an issue for better pybind11 docs if doesn't exist? I'd like to merge&close this PR.

See: #1236

**Pull request merged**
