### PR TITLE
Update basix installation

### PR DESCRIPTION
**Pull request by jorgensd**
Use the new two-stage installation

### CODE REVIEW

**Comment by jhale** [comment]
I already tried but got it wrong anyway. I'll clean up the mess and push back to here.

**Comment by jhale** [comment]
We're getting a runtime linking error on importing dolfinx.cpp.

Should we be linking to `basix` here?

https://github.com/FEniCS/dolfinx/blob/master/python/CMakeLists.txt#L45

The tests seem to run so I'm a little confused.

**Comment by garth-wells** [comment]
It might be a problem with JIT - probably need to add a Basix pkg-config file, and have dolfinx.pc use it too.

Can you run a test that doesn't call any JIT? (JIT is called to build the coordinate map for meshes).

**Comment by jhale** [comment]
That may be an issue, but this error message is quite explicit that it comes from simply importing `dolfinx.cpp`:

https://github.com/FEniCS/dolfinx/runs/2076621407?check_suite_focus=true#step:10:13

**Pull request merged**
