### PR TITLE
Change create_rectangle to take two dimensional points

### PR DESCRIPTION
**Pull request by jhale**
Discussed in #1873. Consistent with `create_interval` and `create_box`.

### CODE REVIEW

**Comment by garth-wells** [comment]
Are we sure we don't want to allow intervals and rectangles embedded in 3D?

**Comment by jhale** [comment]
Personally, I'd use a mesh generator for anything more complex like that.

A rectangle in 3D would also require specification of a normal to the surface as well.

What do you think?

**Comment by garth-wells** [comment]
> Personally, I'd use a mesh generator for anything more complex like that.
> 
> A rectangle in 3D would also require specification of a normal to the surface as well.
> 
> What do you think?

I has assumed that we did support built-in rectangles in 3D. If we didn't and we don't want to, that's fine with me.

**Comment by jhale** [comment]
You and the user who reported https://github.com/FEniCS/dolfinx/issues/1872 !

**Comment by jhale** [comment]
Fixes #1872 and #1873.

**Pull request merged**
