### PR TITLE
Find UFC without using Python

### PR DESCRIPTION
**Pull request by jhale**
Work in progress.

### CODE REVIEW

**Comment by jhale** [comment]
This should allow e.g.

`cmake ../ -DUFC_INCLUDE_DIR=/path/to/ffcx/ffc/backends/ufc`

Bypassing the Python detection in `FindUFC.cmake` and making dolfinx build and runtime potentially Python-free. However, I'm having an issue running `make`:

    dolfin/CMakeFiles/dolfin.dir/flags.make:12: *** missing separator.  Stop.
    CMakeFiles/Makefile2:255: recipe for target 'dolfin/CMakeFiles/dolfin.dir/all' failed
    make[1]: *** [dolfin/CMakeFiles/dolfin.dir/all] Error 2
    Makefile:138: recipe for target 'all' failed
    make: *** [all] Error 2

That I cannot solve. I really can't see what the issue is...

**Comment by garth-wells** [comment]
@jhale not clear from your comment if this is working and ready to merge, or not ready to merge?

**Comment by jhale** [comment]
Not ready, haven't been able to find the problem so far.

**Comment by chrisrichardson** [comment]
Another option would be to merge dolfin and ffc into one repository?

**Comment by jhale** [comment]
I think this is ready to merge now. @chrisrichardson I think this removes at least some of the arguments to merge FFC and DOLFIN, as you can now point DOLFIN at any directory with the required UFC `*.h` files.

**Comment by chrisrichardson** [comment]
To take the opposite point of view - why would you want to point at any (random, old, out of date) `ufc.h` and not the current one. By merging with ffc, you would guarantee it being right.

**Comment by jhale** [comment]
To recap, the main reason for the patch was to work towards a Python-free build of DOLFIN. The old approach required a Python interpreter and a working install of FFC.

I agree your point, it's true. Is it a big problem though? It still seems quite heavy to merge FFC and DOLFIN just to get matching versions of `ufc.h`.

**Pull request merged**
