### PR TITLE
Add isort configuration and non-blocking CI step

### PR DESCRIPTION
**Pull request by jhale**

### CODE REVIEW

**Comment by jorgensd** [comment]
Could we add an `.isort.cfg` file to DOLFINx with the ruleset you use, as the default sort import command (in for instance vscode) will not pick up these options: https://code.visualstudio.com/docs/python/editing#_sort-imports

**Comment by jorgensd** [comment]
@jhale Adding:
```
[isort]
known_first_party = dolfinx
```
to setup.cfg seems to do the trick for vscode

**Comment by jhale** [comment]
That's the plan!

I'm still playing around with it. @garth-wells pointed out to me that isort has some undesirable 'clever' default behaviour depending on the environment. For example, what is in site-packages seems to get put in third-party automatically.

**Comment by jhale** [comment]
@jorgensd Does this branch work properly in vscode?

**Comment by jorgensd** [comment]
> @jorgensd Does this branch work properly in vscode?

Yes, this seems to be working with vscode (Tested demo_elasticity.py and demo_gmsh.py)

**Pull request merged**
