### PR TITLE
Mixed dimension assembly in C++ and form independence for subdomains

### LINKED ISSUE #3113: `dolfinx::fem::create_form` does not support entity-maps
### Summarize the issue

The submesh support in the C++ interface is lacking. One of the issues is that `dolfinx::fem::create_form`, which we usually call in the C++ interface, does not support entity_maps.
https://github.com/FEniCS/dolfinx/blob/main/cpp/dolfinx/fem/utils.h#L621-L657

### How to reproduce the bug

Cannot pass entity_maps to create_form

### Minimal Example (Python)

_No response_

### Output (Python)

_No response_

### Version

main branch

### DOLFINx git commit

_No response_

### Installation

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jorgensd**
This PR exposes the mixed (dimensional) assembly functions to C++ and adds a demo.

Would resolve #3113.

This PR also simplifies the newly created mesh independent form creation (#3263) such that the user can send in integration entities.

Added additional test that exposes this feature in the context of sub-meshes for a rank-1 tensor.

### CODE REVIEW

**Review by jpdean — COMMENTED** [review]
Looks good! Just a few small comments :)

**Comment by jpdean** [comment]
Maybe the description could be updated to remove the comment on shared pointers?

**Comment by jorgensd** [comment]
> Maybe the description could be updated to remove the comment on shared pointers?

Addressed and all other comments have been addressed as well.

**Review by jpdean — APPROVED** [review]
Looks good! :)

**Review by chrisrichardson — APPROVED** [review]

**Pull request merged**
