### PR TITLE
Switch to spdlog

### PR DESCRIPTION
**Pull request by chrisrichardson**
* Remove `loguru` and replace with `spdlog`

### CODE REVIEW

**Comment by jhale** [comment]
This looks good to me apart from having to turn off some warnings. Would it be possible to only turn them off only on GCC? Then we'll still might get some coverage on LLVM/clang toolchains like oneAPI, or people developing on macOS.

**Comment by chrisrichardson** [comment]
Yes I think so.

**Comment by garth-wells** [comment]
> This looks good to me apart from having to turn off some warnings. Would it be possible to only turn them off only on GCC (I was told by Chris this only comes up on GCC)? Then we'll still might get some coverage on LLVM/clang toolchains like oneAPI, or people developing on macOS.

I don't need to disable the warnings with gcc-14.

**Review by garth-wells — APPROVED** [review]
Will need to add spdlog to Dockerfiles, Spack, Debian and conda.

**Comment by chrisrichardson** [comment]
I already added to Docker files, but will need rebuilding.

**Comment by jhale** [comment]
Looks good to me, we can deal with packaging afterwards.

**Comment by garth-wells** [comment]
Resolves #3195

**Pull request merged**
