### PR TITLE
Docker simplify (phase 2)

### PR DESCRIPTION
**Pull request by garth-wells**
Use a virtual env in the Dockerfile for installing dependencies. This is nicer than overwriting system Python packages when installing/updating. Will also allow advanced users to test Python package versions more freely.

### CODE REVIEW

**Comment by jorgensd** [comment]
I think this is a rather intrusive change, as all CIs must change from `python3` to `python` for running code. Can't we use an alias so that we keep some backwards compatibility? I am not saying we should use venv, but is there a point of having another `python3` in that environment, as it is bound to cause confusion.

All my CIs will now fail and need adjustment, and those that are customized to test against both stable and nightly can no longer be merged into a build matrix without extra arguments.

**Comment by garth-wells** [comment]
Why would a change `python3` -> `python` be required?

**Comment by jorgensd** [comment]
> Why would a change `python3` -> `python` be required?

I inferred that from the changes in the CI, where you have replaced `python3 -m pip` with `pip` and `python3` with `python`. Please let me know if I am mistaken, or if there is another motivation for this change.

**Comment by francesco-ballarin** [comment]
Will the script at https://github.com/FEniCS/dolfinx/blob/main/docker/dolfinx-real-mode (and similarly `dolfinx-complex-mode`) need adjustament?

I guess I am a bit confused of what having a `venv` will mean now for real vs complex build.

**Comment by garth-wells** [comment]
> > Why would a change `python3` -> `python` be required?
> 
> I inferred that from the changes in the CI, where you have replaced `python3 -m pip` with `pip` and `python3` with `python`. Please let me know if I am mistaken, or if there is another motivation for this change.

There should be no change required. 

`python3 -m pip` is visual noise when `pip` is enough.

**Comment by jorgensd** [comment]
> > > Why would a change `python3` -> `python` be required?
> > 
> > 
> > I inferred that from the changes in the CI, where you have replaced `python3 -m pip` with `pip` and `python3` with `python`. Please let me know if I am mistaken, or if there is another motivation for this change.
> 
> There should be no change required.
> 
> `python3 -m pip` is visual noise when `pip` is enough.

I dont necessarily agree, as by running pip you do not know what Python installation you are using.

Good to know that no changes are required. Is there a specific reason for the build docker and test Ci failing

**Pull request merged**
