### PR TITLE
Make options required if enabled.

### PR DESCRIPTION
**Pull request by jhale**
This is one way to address https://github.com/FEniCS/dolfinx/issues/3011

The user must explicitly enable optional dependencies.

### CODE REVIEW

**Comment by jhale** [comment]
This retains the previous behaviour while allowing package maintainers to explicitly ensure optional dependencies are found. @garth-wells I didn't totally understand your point, perhaps I've missed something so ping me.

**Comment by garth-wells** [comment]
> This retains the previous behaviour while allowing package maintainers to explicitly ensure optional dependencies are found. @garth-wells I didn't totally understand your point, perhaps I've missed something so ping me.

PR has changed between my comment and the above comment.

I'm not sure the proposed change is super maintainable. How about for each optional package  we add a `FOO_REQUIRED` variable. If the user explicitly sets `DOLFINX_ENABLE_FOO`, then `FOO_REQUIRED` is set to `true`. This keeps the logic close to the package-related code in the CMake file and lets CMake do the error handling.

**Comment by garth-wells** [comment]
@jhale how this approach: https://github.com/FEniCS/dolfinx/tree/garth/cmake-config?

**Comment by jhale** [comment]
Superseded by #3024

**Pull request closed without merging**
