### PR TITLE
[WIP] C++ unit testing might be broken in parallel on circleci

### PR DESCRIPTION
**Pull request by francesco-ballarin**
Associated to issue #576 .

The silly test should be failing in parallel, as not all processes have rank 0.

I marked this as WIP to prevent merge, as this PR is only supposed to try and reproduce the issue that occured while testing #573, but should be discarded without merge after fixing.

### CODE REVIEW

**Comment by francesco-ballarin** [comment]
Current failure is unrelated.

**Comment by francesco-ballarin** [comment]
Latest (successful) CI run confirms that CI is affected by #576

**Comment by IgorBaratta** [comment]
The test is now failing as expected.

**Comment by IgorBaratta** [comment]
The test is now failing as expected.

**Pull request closed without merging**
