### PR TITLE
Use boost::filesystem instead of std::filesystem for compatibility with gcc < 9

### PR DESCRIPTION
**Pull request by francesco-ballarin**

### CODE REVIEW

**Comment by chrisrichardson** [comment]
I think this can be fixed by linking with `-lstdc++fs` rather than going back to boost.

**Comment by michalhabera** [comment]
I do not have a strict opinion here, because I always work with new tools and compiler. Google suggests https://stackoverflow.com/questions/53201991/how-to-use-stdfilesystem-on-gcc-8

**Comment by francesco-ballarin** [comment]
> I think this can be fixed by linking with `-lstdc++fs` rather than going back to boost.

This is true, but then I would argue that we should be consistent across the codebase. Right now we are using both boost and std.

**Comment by garth-wells** [comment]
Might also be an issue with Intel compilers. Not very nice if users need to add a flag by hand.

**Comment by garth-wells** [comment]
I suggest we merge this, and make the switch to `std::filesystem` once gcc 9 is more widespread.

**Pull request merged**
