### PR TITLE
MeshValueCollection from arrays

### PR DESCRIPTION
**Pull request by michalhabera**
Slightly improved version of #467 . This enables completely file-free gmsh-to-dolfinx workflow, including boundaries and subdomains tagging.

### CODE REVIEW

**Comment by michalhabera** [comment]
@francesco-ballarin @iitrabhi I am having the test hanging in parallel. Do you see where the bug is?

**Comment by garth-wells** [comment]
I did recently find some bugs in `MeshValueCollection` were is was calling topology/connectivity creation functions (which are collective) from inside a `set` function. Make sure all collective calls are in the constructor.

**Comment by francesco-ballarin** [comment]
@michalhabera I believe that line 225 should read
```
for (auto& m : mesh::MeshRange(*mesh, _dim, mesh::MeshRangeType::ALL))
```
as we did in MeshFunction.h. In this way, tests pass for me in parallel.

**Comment by michalhabera** [comment]
Thanks @francesco-ballarin . Fixed now without mesh iterators. Pure loop is now more explicit in iteration over ghosts too.

**Pull request merged**
